import { Agent } from "../../core/agent";
import {
  AgentRole,
  Artifact,
  ArtifactType,
  ProjectState,
  Task,
} from "../../core/types";

/**
 * Agent 6: Accessibility Specialist
 *
 * Ensures the application meets WCAG 2.1 AA standards.
 * Audits components for keyboard navigation, screen reader support,
 * color contrast, and focus management.
 */
export class AccessibilityAgent extends Agent {
  readonly role = AgentRole.AccessibilitySpecialist;
  readonly name = "Accessibility Specialist";
  readonly description =
    "Audits and fixes accessibility issues, ensures WCAG 2.1 AA compliance, and provides inclusive design guidance";
  readonly capabilities = [
    "wcag-audit",
    "aria-labels",
    "keyboard-navigation",
    "screen-reader-testing",
    "color-contrast",
    "focus-management",
  ];

  getSystemPrompt(): string {
    return `You are an Accessibility Specialist on a 13-agent AI engineering team.
Your job is to:
- Audit every component for WCAG 2.1 AA compliance
- Add appropriate ARIA attributes (roles, labels, live regions)
- Ensure full keyboard navigability for all interactive elements
- Verify color contrast meets minimum ratios (4.5:1 for text, 3:1 for large text)
- Implement focus management for modals, dropdowns, and route changes
- Test with screen reader patterns
- Flag and fix any accessibility violations`;
  }

  async execute(task: Task, state: ProjectState): Promise<Artifact[]> {
    this.log("Running accessibility audit...");
    const artifacts: Artifact[] = [];

    // A11y audit checklist
    const auditChecklist = {
      categories: [
        {
          name: "Perceivable",
          checks: [
            { rule: "All images have descriptive alt text", status: "required", wcag: "1.1.1" },
            { rule: "Color is not the sole means of conveying information", status: "required", wcag: "1.4.1" },
            { rule: "Text contrast ratio is at least 4.5:1", status: "required", wcag: "1.4.3" },
            { rule: "Content can be resized to 200% without loss", status: "required", wcag: "1.4.4" },
            { rule: "Non-text contrast ratio is at least 3:1", status: "required", wcag: "1.4.11" },
          ],
        },
        {
          name: "Operable",
          checks: [
            { rule: "All functionality available via keyboard", status: "required", wcag: "2.1.1" },
            { rule: "No keyboard traps", status: "required", wcag: "2.1.2" },
            { rule: "Focus order is logical and intuitive", status: "required", wcag: "2.4.3" },
            { rule: "Focus is visible on all interactive elements", status: "required", wcag: "2.4.7" },
            { rule: "Skip navigation link is present", status: "required", wcag: "2.4.1" },
            { rule: "Page titles are descriptive", status: "required", wcag: "2.4.2" },
          ],
        },
        {
          name: "Understandable",
          checks: [
            { rule: "Page language is declared in HTML", status: "required", wcag: "3.1.1" },
            { rule: "Form inputs have associated labels", status: "required", wcag: "3.3.2" },
            { rule: "Error messages identify the field and suggest fix", status: "required", wcag: "3.3.3" },
            { rule: "Navigation is consistent across pages", status: "required", wcag: "3.2.3" },
          ],
        },
        {
          name: "Robust",
          checks: [
            { rule: "HTML validates without errors", status: "required", wcag: "4.1.1" },
            { rule: "Custom components have proper ARIA roles", status: "required", wcag: "4.1.2" },
            { rule: "Status messages use aria-live regions", status: "required", wcag: "4.1.3" },
          ],
        },
      ],
    };

    artifacts.push(
      this.createArtifact(
        ArtifactType.Specification,
        "docs/accessibility-audit.json",
        JSON.stringify(auditChecklist, null, 2),
        "WCAG 2.1 AA accessibility audit checklist"
      )
    );

    // Accessible component utilities
    const a11yUtils = `/**
 * Accessibility utility hooks and helpers
 * Generated by the Accessibility Specialist agent
 */

import { useEffect, useRef, useCallback } from "react";

/** Trap focus within a container (for modals and dialogs) */
export function useFocusTrap(active: boolean) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!active || !containerRef.current) return;

    const container = containerRef.current;
    const focusable = container.querySelectorAll<HTMLElement>(
      'a[href], button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])'
    );
    const first = focusable[0];
    const last = focusable[focusable.length - 1];

    function handleKeyDown(e: KeyboardEvent) {
      if (e.key !== "Tab") return;
      if (e.shiftKey) {
        if (document.activeElement === first) { e.preventDefault(); last?.focus(); }
      } else {
        if (document.activeElement === last) { e.preventDefault(); first?.focus(); }
      }
    }

    container.addEventListener("keydown", handleKeyDown);
    first?.focus();

    return () => container.removeEventListener("keydown", handleKeyDown);
  }, [active]);

  return containerRef;
}

/** Announce a message to screen readers via aria-live */
export function useAnnounce() {
  const announce = useCallback((message: string, priority: "polite" | "assertive" = "polite") => {
    const el = document.createElement("div");
    el.setAttribute("aria-live", priority);
    el.setAttribute("aria-atomic", "true");
    el.setAttribute("role", priority === "assertive" ? "alert" : "status");
    el.className = "sr-only";
    el.textContent = message;
    document.body.appendChild(el);
    setTimeout(() => document.body.removeChild(el), 1000);
  }, []);

  return announce;
}

/** Hook to manage roving tabindex for composite widgets (tabs, toolbars, etc.) */
export function useRovingTabIndex(itemCount: number) {
  const activeIndex = useRef(0);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      let newIndex = activeIndex.current;
      if (e.key === "ArrowDown" || e.key === "ArrowRight") {
        e.preventDefault();
        newIndex = (activeIndex.current + 1) % itemCount;
      } else if (e.key === "ArrowUp" || e.key === "ArrowLeft") {
        e.preventDefault();
        newIndex = (activeIndex.current - 1 + itemCount) % itemCount;
      } else if (e.key === "Home") {
        e.preventDefault();
        newIndex = 0;
      } else if (e.key === "End") {
        e.preventDefault();
        newIndex = itemCount - 1;
      }
      activeIndex.current = newIndex;
    },
    [itemCount]
  );

  return { activeIndex, handleKeyDown };
}

/** Screen-reader only CSS class (include in global styles) */
export const srOnlyCss = \`.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}\`;
`;

    artifacts.push(
      this.createArtifact(
        ArtifactType.SourceCode,
        "src/client/utils/a11y.ts",
        a11yUtils,
        "Accessibility utility hooks: focus trap, screen reader announcements, roving tabindex"
      )
    );

    this.log(`Audit checklist: ${auditChecklist.categories.reduce((sum, c) => sum + c.checks.length, 0)} rules across ${auditChecklist.categories.length} categories`);
    return artifacts;
  }
}
