import { Agent } from "../../core/agent";
import {
  AgentRole,
  Artifact,
  ArtifactType,
  ProjectState,
  Task,
} from "../../core/types";

/**
 * Agent 8: Database Engineer
 *
 * Designs schemas, writes migrations, defines models,
 * and optimizes queries. Handles the data layer.
 */
export class DatabaseEngineerAgent extends Agent {
  readonly role = AgentRole.DatabaseEngineer;
  readonly name = "Database Engineer";
  readonly description =
    "Designs database schemas, writes migrations, defines data models, and optimizes queries";
  readonly capabilities = [
    "schema-design",
    "migrations",
    "data-modeling",
    "query-optimization",
    "indexing-strategy",
    "relationships",
  ];

  getSystemPrompt(): string {
    return `You are a senior Database Engineer on a 9-agent AI engineering team.
Your job is to:
- Design normalized database schemas based on requirements
- Define data models with proper types, constraints, and relationships
- Write migration scripts for schema creation and evolution
- Design indexes for common query patterns
- Implement seed data for development
- Ensure data integrity with foreign keys, unique constraints, and check constraints`;
  }

  async execute(task: Task, state: ProjectState): Promise<Artifact[]> {
    this.log("Designing database schema and models...");
    const artifacts: Artifact[] = [];

    // Schema definition
    const schema = {
      tables: {
        users: {
          columns: {
            id: { type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
            email: { type: "varchar(255)", unique: true, nullable: false },
            password_hash: { type: "varchar(255)", nullable: false },
            name: { type: "varchar(255)", nullable: false },
            avatar_url: { type: "text", nullable: true },
            role: { type: "varchar(50)", default: "'user'", nullable: false },
            email_verified: { type: "boolean", default: "false" },
            created_at: { type: "timestamptz", default: "now()", nullable: false },
            updated_at: { type: "timestamptz", default: "now()", nullable: false },
          },
          indexes: ["CREATE INDEX idx_users_email ON users(email)"],
        },
        sessions: {
          columns: {
            id: { type: "uuid", primaryKey: true, default: "gen_random_uuid()" },
            user_id: { type: "uuid", nullable: false, references: "users(id) ON DELETE CASCADE" },
            refresh_token: { type: "varchar(500)", nullable: false },
            expires_at: { type: "timestamptz", nullable: false },
            created_at: { type: "timestamptz", default: "now()", nullable: false },
          },
          indexes: [
            "CREATE INDEX idx_sessions_user_id ON sessions(user_id)",
            "CREATE INDEX idx_sessions_token ON sessions(refresh_token)",
          ],
        },
        audit_log: {
          columns: {
            id: { type: "bigserial", primaryKey: true },
            user_id: { type: "uuid", nullable: true, references: "users(id) ON DELETE SET NULL" },
            action: { type: "varchar(100)", nullable: false },
            entity_type: { type: "varchar(100)", nullable: false },
            entity_id: { type: "varchar(255)", nullable: true },
            metadata: { type: "jsonb", default: "'{}'" },
            ip_address: { type: "inet", nullable: true },
            created_at: { type: "timestamptz", default: "now()", nullable: false },
          },
          indexes: [
            "CREATE INDEX idx_audit_user_id ON audit_log(user_id)",
            "CREATE INDEX idx_audit_created_at ON audit_log(created_at)",
          ],
        },
      },
    };

    artifacts.push(
      this.createArtifact(
        ArtifactType.Schema,
        "docs/database-schema.json",
        JSON.stringify(schema, null, 2),
        "Database schema definition with tables, columns, constraints, and indexes"
      )
    );

    // SQL migration
    const migration = `-- Migration: 001_initial_schema
-- Generated by Database Engineer Agent

BEGIN;

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  avatar_url TEXT,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  email_verified BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_email ON users(email);

-- Sessions table
CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token VARCHAR(500) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_token ON sessions(refresh_token);

-- Audit log table
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id VARCHAR(255),
  metadata JSONB DEFAULT '{}',
  ip_address INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_user_id ON audit_log(user_id);
CREATE INDEX idx_audit_created_at ON audit_log(created_at);

-- Updated-at trigger
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

COMMIT;
`;

    artifacts.push(
      this.createArtifact(
        ArtifactType.Migration,
        "migrations/001_initial_schema.sql",
        migration,
        "Initial database migration with users, sessions, and audit log tables"
      )
    );

    // Seed data
    const seed = `-- Seed data for development
-- Generated by Database Engineer Agent

INSERT INTO users (id, email, password_hash, name, role, email_verified) VALUES
  ('00000000-0000-0000-0000-000000000001', 'admin@example.com', '$2b$10$placeholder_hash', 'Admin User', 'admin', true),
  ('00000000-0000-0000-0000-000000000002', 'user@example.com', '$2b$10$placeholder_hash', 'Test User', 'user', true)
ON CONFLICT (email) DO NOTHING;
`;

    artifacts.push(
      this.createArtifact(
        ArtifactType.Migration,
        "migrations/seed.sql",
        seed,
        "Development seed data"
      )
    );

    this.log(`Designed ${Object.keys(schema.tables).length} tables with indexes and migration`);
    return artifacts;
  }
}
